# Read the Docs configuration file
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
    post_install:
      # Install project dependencies
      - poetry config virtualenvs.create false
      - poetry install --with docs --no-interaction

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false  # Set to true after initial setup
  version: "6.2.1"


# Build PDF & ePub
formats:
  - pdf
  - epub
  - htmlzip

# Submodules (if any)
submodules:
  include: []
  recursive: false
