name: Performance Tests

on:
  pull_request:
    branches: ["master", "main"]
    paths:
      - 'energy_transformer/**/*.py'
      - 'tests/performance/**/*.py'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  performance-tests:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-perf-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install --no-interaction --with dev

      - name: Run performance tests on base branch
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          poetry run pytest tests/performance/ -v --benchmark-only --benchmark-json=base-benchmark.json

      - name: Run performance tests on PR branch
        run: |
          git checkout ${{ github.event.pull_request.head.sha }}
          poetry run pytest tests/performance/ -v --benchmark-only --benchmark-json=pr-benchmark.json

      - name: Compare results
        run: |
          poetry run pytest-benchmark compare base-benchmark.json pr-benchmark.json --threshold=10 | tee comparison.txt

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comparison = fs.readFileSync('comparison.txt', 'utf8');
            const body = `## Performance Test Results\n\n\`\`\`\n${comparison}\n\`\`\``;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
